module.exports = {
  content: ['./src/**/*.{js,ts,jsx,tsx}'],
  corePlugins: {
    preflight: false,
  },
  theme: {
    extend: {
      colors: {
        primary: '#004425',
        'primary-container': '#135d38',
        'on-primary': '#ffffff',
        'on-primary-container': '#8dd4a5',
        'primary-fixed': '#abf3c2',
        'primary-fixed-dim': '#8fd6a7',
        secondary: '#006d40',
        'secondary-container': '#8ef5b5',
        'on-secondary-container': '#007243',
        'secondary-fixed': '#91f8b8',
        'secondary-fixed-dim': '#74db9d',
        tertiary: '#5c2f00',
        'tertiary-container': '#7d4200',
        'tertiary-fixed': '#ffdcc3',
        'tertiary-fixed-dim': '#ffb77d',
        'on-tertiary': '#ffffff',
        'on-tertiary-fixed': '#2f1500',
        'on-tertiary-fixed-variant': '#6e3900',
        surface: '#f3fcf3',
        'surface-dim': '#d3dcd4',
        'surface-bright': '#f3fcf3',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#edf6ee',
        'surface-container': '#e7f0e8',
        'surface-container-high': '#e2eae2',
        'surface-container-highest': '#dce5dd',
        'on-surface': '#151d19',
        'on-surface-variant': '#404941',
        outline: '#707971',
        'outline-variant': '#bfc9bf',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'inverse-surface': '#2a322d',
        'inverse-on-surface': '#eaf3eb',
      },
    },
  },
};
