/**
 * 企业后台的**运营类种子数据**：工单、农资产品、结算单、履约事件（原型 Mock，逐字迁入）。
 *
 * 自 admin.seed.ts 按红线 R10（单文件 ≤ 500 行）拆出——数据未做任何改动。
 * 金额仍是**元（浮点）**，由 `seed.ts` 统一转成「分」入库（红线 R7）。
 *
 * ⚠️ 涉及虚构字段（窜货熔断：fleeStatus 系；示意距离：distanceKm）已按
 *    AGENTS.md「本期不做」口径从类型与种子数据移除；distanceKm 属示意值（无地图服务）。
 */

import type {
  AmoebaSettlement,
  FulfillmentEvent,
  SupplyProduct,
  WorkOrder,
} from '@hnhall/shared';

/**
 * 企业后台运营数据（迁移期，与 `AdminSeed` 同源同口径）。
 */
export class AdminOpsSeed {
  workOrders: WorkOrder[] = [
    {
      id: '#ORD-20241028-0914',
      farmerName: '刘建国',
      coopName: '安沙联丰水稻合作社',
      phone: '138****3910',
      location: '安沙镇黄旗村04组机耕道东侧',
      gridCode: 'AS-HQ-04G',
      crop: '晚稻分蘖末期',
      acreage: 25.4,
      cropStage: '分蘖末期',
      symptom: '疑似稻飞虱伴随纹枯病斑',
      serviceCategory: 'diagnosis',
      serviceCategoryText: '植保上门诊断 (紧急)',
      urgency: 'critical',
      urgencyText: '紧急加急',
      specialSubsidy: '农机补贴专项',
      reportedTime: '2024-10-28 09:12:40',
      waitingMinutes: 28,
      requestedAction: '技师2小时内实地踏勘+开处方药',
      status: 'pending_dispatch',
      statusText: '算力匹配中',
      currentStep: 1,
      matchedCandidates: [
        {
          id: 'cand-001',
          name: '张茂林 (农艺师)',
          phone: '139****2210',
          title: '高级植保师',
          avatar:
            'https://lh3.googleusercontent.com/aida-public/AB6AXuAo9nFxQhBBbek7LKbtOgaKd5768mxKCDJhBexUHKqZaQlgjSAdreqs7Gasmim5Zzr1d_7_aA21F_FTTIK1bfCrpTB-RGZSFOfOsX7MjaTo0mgUttFJrD8CB6Vyj1xYzItT-JpLj8k3P2FmP3AcrI5Isax3R0-xnWKKyRHT6jDLZz5qF8cbCLyZcLt_LsGV3UFj-vqJ68GRNzI5zkSoUHhzle-X8PrU4KuHjDbRvSd2Km7Q5qpb3-_8',
          distanceKm: 2.1,
          estimatedArrivalMin: 22,
          matchScore: 98.6,
          dailyLoad: 1,
          maxDailyLoad: 4,
          rating: 99.8,
          jobCount: 420,
          expertiseTag: '水稻病害S级专精',
          statusText: '就近待命中',
          isPrimary: true,
          licenseVerified: '湘20240018已校验有效 (至2027年)',
        },
        {
          id: 'cand-002',
          name: '李国锋 (持证农艺师)',
          phone: '137****6123',
          title: '民用无人机驾驶员',
          avatar:
            'https://lh3.googleusercontent.com/aida-public/AB6AXuBQ2rvcDQcZnOiqLgMTUrM7uPxbt7Tdd6VQYiKZVTjHNi57vqDvScY3Jw1dYY-2FosE-vc_bJWBY4VCW3FmS9C4DzRBToV-2NyX42Jxr6BaMFx2xLZDXRzjbh7LELi9dWm7y7TLgJxg0xn86A5REW1Hut3AhadXpsQlNZwvaw4nL1F1QQQnUy-dFVw2TvhkeeXG6H8El5idujJfIqZVdMGyUUzaXWImhDNfF9KlU7BmczPN8X-0n6Pl',
          distanceKm: 3.8,
          estimatedArrivalMin: 35,
          matchScore: 91.2,
          dailyLoad: 2,
          maxDailyLoad: 4,
          rating: 99.1,
          jobCount: 310,
          expertiseTag: '飞防经验丰富',
          statusText: '2单进行中 (可协调)',
          licenseVerified: '湘20230198已校验有效',
        },
        {
          id: 'cand-003',
          name: '陈惠芬 (资深植保研究员)',
          phone: '136****9988',
          title: '研究员级高级农艺师',
          avatar:
            'https://lh3.googleusercontent.com/aida-public/AB6AXuDhqEeKp9F10UHxO2QI4bBHy5yDuSlofdFJvzrItvEA8GWXnchomlnfJc5AD7ZEN6njKU5qzQbYMStqMei2A5o9xVl_T42w4Eimu69j_etL3OKyX6JEC40ABQSl3EGXzS9N8frXQbK_T0bgYfkMgzziImIcSVUadRdoKQW0sQT60R3WNe3ZHVPvE7bR81ZkI47wYwhok8ancNLnVyv3-4xFzKYAy7MxNYuAvC0gtqjrgPb_unSzbE1Y',
          distanceKm: 5.4,
          estimatedArrivalMin: 45,
          matchScore: 89.5,
          dailyLoad: 0,
          maxDailyLoad: 2,
          rating: 100,
          jobCount: 512,
          expertiseTag: '全县专家组特邀',
          statusText: '专家会诊待命',
          licenseVerified: '国家农业技术资格特级',
        },
      ],
    },
    {
      id: '#ORD-20241028-0902',
      farmerName: '周宏福',
      coopName: '高桥镇白石村种植园',
      phone: '159****8812',
      location: '高桥镇白石冲水库南侧坡地',
      gridCode: 'GQ-BS-02',
      crop: '柑橘蜜桔',
      acreage: 18.0,
      cropStage: '果实膨大期',
      symptom: '炭疽病叶片黄化现场诊断',
      serviceCategory: 'diagnosis',
      serviceCategoryText: '常规植保诊断',
      urgency: 'normal',
      urgencyText: '常规工单',
      reportedTime: '2024-10-28 08:30:15',
      waitingMinutes: 48,
      requestedAction: '现场病叶取样+制定配方',
      status: 'pending_dispatch',
      statusText: '待调度',
      currentStep: 1,
    },
    {
      id: '#ORD-20241028-0855',
      farmerName: '陈仕强',
      coopName: '路口镇龙泉粮油农场',
      phone: '135****4567',
      location: '路口镇龙泉村老屋场组',
      gridCode: 'LK-LQ-01',
      crop: '油菜冬种基地',
      acreage: 60.0,
      cropStage: '苗期基肥喷洒',
      symptom: '需配置大载重植保无人机双机组',
      serviceCategory: 'drone',
      serviceCategoryText: '精准飞防统防',
      urgency: 'high',
      urgencyText: '飞防统防',
      reportedTime: '2024-10-28 08:00:00',
      waitingMinutes: 60,
      requestedAction: '安排双机组飞防作业',
      status: 'pending_dispatch',
      statusText: '待调度',
      currentStep: 1,
    },
    {
      id: '#ORD-20241028-0840',
      farmerName: '黄德贵',
      coopName: '黄兴镇仙人市村',
      phone: '138****0123',
      location: '黄兴镇仙人市村湾潭组',
      gridCode: 'HX-XR-03',
      crop: '优质水稻',
      acreage: 110.0,
      cropStage: '秋收开镰前',
      symptom: '沃得收割机液压系统保养',
      serviceCategory: 'machinery',
      serviceCategoryText: '农机巡检维保',
      urgency: 'normal',
      urgencyText: '农机巡检',
      reportedTime: '2024-10-28 07:45:00',
      waitingMinutes: 72,
      requestedAction: '农机手急需抢修保养',
      status: 'pending_dispatch',
      statusText: '待调度',
      currentStep: 1,
    },
    {
      id: '#ORD-20241028-0720',
      farmerName: '李先生',
      coopName: '仙人市粮食基地',
      phone: '138****9201',
      location: '黄兴镇仙人市村4组机耕路口',
      gridCode: 'HX-XR-04',
      crop: '晚稻',
      acreage: 40.0,
      cropStage: '灌浆期',
      symptom: '水稻稻飞虱喷施',
      serviceCategory: 'diagnosis',
      serviceCategoryText: '植保诊断与飞防',
      urgency: 'high',
      urgencyText: '加急处理',
      reportedTime: '2024-10-28 07:20:15',
      waitingMinutes: 90,
      requestedAction: '已开具处方，正在飞防中',
      status: 'prescription_issued',
      statusText: '开具处方中',
      currentStep: 4,
      assignedTechnician: {
        id: 'tech-wpg',
        name: '王培根 (持证)',
        phone: '138****9201',
        title: '持证植保机手',
        avatar:
          'https://lh3.googleusercontent.com/aida-public/AB6AXuAo9nFxQhBBbek7LKbtOgaKd5768mxKCDJhBexUHKqZaQlgjSAdreqs7Gasmim5Zzr1d_7_aA21F_FTTIK1bfCrpTB-RGZSFOfOsX7MjaTo0mgUttFJrD8CB6Vyj1xYzItT-JpLj8k3P2FmP3AcrI5Isax3R0-xnWKKyRHT6jDLZz5qF8cbCLyZcLt_LsGV3UFj-vqJ68GRNzI5zkSoUHhzle-X8PrU4KuHjDbRvSd2Km7Q5qpb3-_8',
        distanceKm: 0,
        estimatedArrivalMin: 0,
        matchScore: 99.0,
      },
      prescriptionCode: 'RX-HN-20241028-0842',
      prescriptionContent: '吡蚜酮+烯啶虫胺组合配方',
      watermarkVerified: true,
      watermarkTime: '08:05:12',
      watermarkGps: '29.214N, 112.441E',
    },
    {
      id: '#ORD-20241028-0610',
      farmerName: '赵女士',
      coopName: '龙泉生态油茶园',
      phone: '139****1182',
      location: '路口镇龙泉村北岭组山坳',
      gridCode: 'LK-LQ-02',
      crop: '油茶',
      acreage: 55.0,
      cropStage: '盛果期',
      symptom: '油茶炭疽病综合统防',
      serviceCategory: 'drone',
      serviceCategoryText: '精准飞防作业',
      urgency: 'normal',
      urgencyText: '已结单',
      reportedTime: '2024-10-28 06:10:00',
      waitingMinutes: 0,
      requestedAction: '已完成农户手写签字验收',
      status: 'completed',
      statusText: '已验收结单',
      currentStep: 5,
      assignedTechnician: {
        id: 'tech-tjx',
        name: '唐建新 (高级农艺师)',
        phone: '139****1182',
        title: '高级农艺师',
        avatar:
          'https://lh3.googleusercontent.com/aida-public/AB6AXuDLhf11MbzfcGFwLwmP7tWfOFXMQEIxtPPJ0ll39e5bls2EyH7xflkDbZn9W71aJZBP_Or21MpLXVufmdu0fYuJwI2XXuXQyld_dBqt8JtgcfZxdjSsCmOAuCKWllI7XoXfzhVceonKOAN-s9wuPpxBDZWMIs08QBz5-TTkdEQ485MwpcoyUhT6O5c8KpRNmS9kXluQfyFLeBaWF5Td62GSElOVpU7hNBb_RcRqs_wSNaaEyCdRRrTb',
        distanceKm: 0,
        estimatedArrivalMin: 0,
        matchScore: 99.5,
      },
      prescriptionCode: 'RX-HN-20241028-0711',
      watermarkVerified: true,
      watermarkTime: '06:55:00',
      signedAt: '08:45:00',
      settlementAmount: 420.0,
    },
    {
      id: '#ORD-20241028-0589',
      farmerName: '邓发财',
      coopName: '水塘村育秧基地',
      phone: '135****6677',
      location: '安沙镇水塘村6组提灌站旁',
      gridCode: 'AS-ST-06',
      crop: '晚稻',
      acreage: 12.0,
      cropStage: '秧苗立枯病排查',
      symptom: '立枯黄斑猝倒',
      serviceCategory: 'diagnosis',
      serviceCategoryText: '急诊排查',
      urgency: 'critical',
      urgencyText: '接单超时预警',
      reportedTime: '2024-10-28 05:40:00',
      waitingMinutes: 120,
      requestedAction: '超时15分未确认，需紧急改派',
      status: 'exception',
      statusText: '接单超时预警',
      currentStep: 2,
    },
  ];

  supplyProducts: SupplyProduct[] = [
    {
      id: 'prod-001',
      name: '75% 肟菌·戊唑醇悬浮剂',
      spec: '100ml / 瓶 · 极速成膜防白粉',
      iconType: 'eco',
      registrationNumber: 'PD20210892',
      registrationNotes: '三证齐备 · 农业部在册',
      batchNumber: 'HN-20240315-A',
      manufactureDate: '2024-03-15 出厂',
      totalCoded: 85000,
      totalCodedUnit: '袋',
      scanCount: 64210,
      scanCountUnit: '瓶',
      scanProgressPct: 75.5,

      prescriptionCommissionRate: 12.5,
      monthlySales: 48200.0,
      traceabilityNodes: [
        { time: '2024-03-15 10:24', desc: '出厂赋码已同步至国家农药质量追溯云' },
        { time: '2024-03-18 14:10', desc: '华农智服常德区域前置仓验收上架' },
        { time: '2024-04-12 09:30', desc: '技师张师傅开具数字植保处方绑定出库' },
      ],
    },
    {
      id: 'prod-002',
      name: '200g/L 氯虫苯甲酰胺悬浮剂',
      spec: '20ml / 支 · 针对抗性水稻螟虫',
      iconType: 'pest_control',
      registrationNumber: 'PD20182470',
      registrationNotes: '三证齐备 · 国家专审',
      batchNumber: 'HN-20240402-C',
      manufactureDate: '2024-04-02 出厂',
      totalCoded: 120000,
      totalCodedUnit: '支',
      scanCount: 98400,
      scanCountUnit: '支',
      scanProgressPct: 82.0,

      prescriptionCommissionRate: 15.0,
      monthlySales: 62800.0,
      traceabilityNodes: [
        { time: '2024-04-02 08:30', desc: '原药纯度经农业部指定检测合格入库' },
        { time: '2024-04-05 11:15', desc: '智能物联网防伪监管码在线激活完成' },
        { time: '2024-04-15 16:00', desc: '益阳赫山飞防队集中领药开具电子监管密令' },
      ],
    },
    {
      id: 'prod-003',
      name: '40% 咪鲜胺水乳剂',
      spec: '500ml / 瓶 · 炭疽病高效广谱',
      iconType: 'warning',
      registrationNumber: 'PD20193108',
      registrationNotes: '三证齐备 · 生产在检',
      batchNumber: 'HN-20240218-B',
      manufactureDate: '2024-02-18 出厂',
      totalCoded: 40000,
      totalCodedUnit: '瓶',
      scanCount: 19830,
      scanCountUnit: '瓶',
      scanProgressPct: 49.5,

      prescriptionCommissionRate: 10.0,
      monthlySales: 19830.0,
      traceabilityNodes: [
        { time: '2024-02-18 13:00', desc: '生产批次下线，预设投放区域为岳阳' },
        { time: '2024-03-01 10:20', desc: '流转至长沙物流周转中心' },
        { time: '2024-04-10 14:22', desc: '异常触发：在常德市鼎城区出现密集扫码' },
      ],
    },
    {
      id: 'prod-004',
      name: '高活性聚谷氨酸海藻精生根肥',
      spec: '1000ml / 桶 · 土壤团粒修复',
      iconType: 'fluid_balance',
      registrationNumber: '农肥准字2023-4811',
      registrationNotes: '特肥专号 · 绿标免税',
      batchNumber: 'HN-20240410-D',
      manufactureDate: '2024-04-10 出厂',
      totalCoded: 35000,
      totalCodedUnit: '桶',
      scanCount: 27650,
      scanCountUnit: '桶',
      scanProgressPct: 79.0,

      prescriptionCommissionRate: 8.0,
      monthlySales: 38400.0,
      traceabilityNodes: [
        { time: '2024-04-10 09:00', desc: '生物有机活性检测达标合格' },
        { time: '2024-04-14 10:40', desc: '水肥一体化服务车间直配到田' },
      ],
    },
    {
      id: 'prod-005',
      name: '5% 虱螨脲微乳剂',
      spec: '250ml / 瓶 · 杀卵抑脱皮长效',
      iconType: 'shield',
      registrationNumber: 'PD20221943',
      registrationNotes: '三证齐备 · 生产备案',
      batchNumber: 'HN-20240328-E',
      manufactureDate: '2024-03-28 出厂',
      totalCoded: 50000,
      totalCodedUnit: '瓶',
      scanCount: 32100,
      scanCountUnit: '瓶',
      scanProgressPct: 64.2,

      prescriptionCommissionRate: 11.0,
      monthlySales: 15290.0,
      traceabilityNodes: [
        { time: '2024-03-28 15:30', desc: '出厂完成全量一物一码赋码' },
        { time: '2024-04-08 09:12', desc: '安沙镇飞防示范站入库登记完毕' },
      ],
    },
  ];

  amoebaSettlements: AmoebaSettlement[] = [
    {
      id: 'amo-001',
      partnerCode: 'HN-ST-0082',
      partnerName: '张师傅',
      partnerAvatarLetter: '张',
      partnerLevel: '黄金合伙人',
      teamName: '汉寿洞庭湖二组',
      menteeStatus: '4 位徒弟技师在编',
      serviceFee: 4200.0,
      prescriptionBonus: 3140.0,
      mentorshipBonus: 1100.0,
      equityDividend: 500.0,
      grossAmount: 8940.0,
      taxWithheld: 268.2,
      netPay: 8671.8,
      status: 'pending',
    },
    {
      id: 'amo-002',
      partnerCode: 'HN-ST-0015',
      partnerName: '李建国',
      partnerAvatarLetter: '李',
      partnerLevel: '先锋领航者',
      teamName: '鼎城常德油茶战区',
      menteeStatus: '6 位徒弟技师在编',
      serviceFee: 5600.0,
      prescriptionBonus: 4820.0,
      mentorshipBonus: 1850.0,
      equityDividend: 800.0,
      grossAmount: 13070.0,
      taxWithheld: 392.1,
      netPay: 12677.9,
      status: 'pending',
    },
    {
      id: 'amo-003',
      partnerCode: 'HN-ST-0129',
      partnerName: '王志强',
      partnerAvatarLetter: '王',
      partnerLevel: '认证飞手技师',
      teamName: '岳阳君山水稻片区',
      menteeStatus: '独立作业技师',
      serviceFee: 3900.0,
      prescriptionBonus: 1890.0,
      mentorshipBonus: 350.0,
      equityDividend: 200.0,
      grossAmount: 6340.0,
      taxWithheld: 190.2,
      netPay: 6149.8,
      status: 'pending',
    },
    {
      id: 'amo-004',
      partnerCode: 'HN-ST-0044',
      partnerName: '陈大明',
      partnerAvatarLetter: '陈',
      partnerLevel: '黄金合伙人',
      teamName: '益阳赫山特作三组',
      menteeStatus: '3 位徒弟技师在编',
      serviceFee: 4850.0,
      prescriptionBonus: 3420.0,
      mentorshipBonus: 980.0,
      equityDividend: 500.0,
      grossAmount: 9750.0,
      taxWithheld: 292.5,
      netPay: 9457.5,
      status: 'pending',
    },
  ];

  fulfillmentEvents: FulfillmentEvent[] = [
    {
      id: 'event-001',
      type: 'check_in',
      title: '农艺师现场打卡签到',
      timestamp: '2分钟前',
      summary: '李国华技师已到达益阳市大通湖千亩水稻田',
      technicianName: '李国华 (农艺师)',
      location: '益阳市大通湖千亩水稻田',
      gps: '29.214N, 112.441E',
      droneModel: '大疆 T50 满载试飞',
      photoUrl:
        'https://lh3.googleusercontent.com/aida-public/AB6AXuBFQMhHJU2sBN02qvJWNWnPCh3e15rfWL5rfOnjzeafwiTGn-4PNlaR-atQ5KfhiksCEmzps-zaA2uzQkAYLRhAy5EPD8eO88EcVIc5XFdcNI1mQbp-btWah6NaFFqMPFd5FC1hQddfszSqSMO-6HPYt9evhOWiX5K_RtYFcfuJmopRV9UaiLx5FtFOOyIyMf-ul4AiwJrkFCGKR2J3fbSF9aBj3_Z_UlIE_EPuVMl6I-6bvsMeSKai',
    },
    {
      id: 'event-002',
      type: 'prescription',
      title: '一物一码出库核验成功',
      timestamp: '8分钟前',
      summary: '订单 #HN-20240414-015 溯源出库完成',
      technicianName: '张茂林',
      location: '长沙县安沙示范站',
      qrTraceCode: '86.10294.041842',
      batchCode: '20240315-A4 · 农药登记证号已挂网',
    },
    {
      id: 'event-003',
      type: 'sign_off',
      title: '农户电子手写签字验收',
      timestamp: '14分钟前',
      summary: '桃江县修山镇 160亩 茶园病虫统防统治竣工',
      technicianName: '唐建新',
      location: '桃江县修山镇茶园',
      rating: 5.0,
      settlementBonus: 420.0,
    },
  ];
}
